'use client'

import { useState } from 'react'
import { Download, Loader2 } from 'lucide-react'
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

interface RedFlag {
  severity: 'critical' | 'high' | 'medium' | 'low'
  category: string
  title: string
  description: string
  evidence?: string[]
  fix?: string
}

interface AuditReport {
  id: string
  toolName: string
  toolPath: string
  score: number
  grade: string
  redFlags: RedFlag[]
  completedAt: string
  findings?: any
}

interface ExportButtonProps {
  report: AuditReport
  format?: 'pdf' | 'markdown'
  tier?: 'free' | 'pro' | 'enterprise'
}

/**
 * Export button for PDF/Markdown reports
 * Pro+ feature
 */
export function ExportButton({
  report,
  format = 'pdf',
  tier = 'free'
}: ExportButtonProps) {
  const [loading, setLoading] = useState(false)

  const isExportAllowed = tier !== 'free'

  const handleExport = async () => {
    if (!isExportAllowed) {
      alert('PDF export is a Pro feature. Please upgrade your plan.')
      return
    }

    setLoading(true)

    try {
      if (format === 'pdf') {
        await exportPDF(report)
      } else {
        await exportMarkdown(report)
      }
    } catch (error) {
      console.error('Export failed:', error)
      alert('Export failed. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <button
      onClick={handleExport}
      disabled={loading || !isExportAllowed}
      className={`
        inline-flex items-center gap-2 px-4 py-2 rounded-lg font-medium transition
        ${!isExportAllowed
          ? 'bg-gray-100 text-gray-400 cursor-not-allowed'
          : 'bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-50'
        }
      `}
      title={!isExportAllowed ? 'Upgrade to Pro for export' : `Export as ${format.toUpperCase()}`}
    >
      {loading ? (
        <Loader2 className="w-4 h-4 animate-spin" />
      ) : (
        <Download className="w-4 h-4" />
      )}
      <span>Export {format.toUpperCase()}</span>
    </button>
  )
}

async function exportPDF(report: AuditReport) {
  const doc = new jsPDF()

  // Header
  doc.setFontSize(20)
  doc.text('User Experience Audit Report', 20, 20)

  doc.setFontSize(12)
  doc.text(`Tool: ${report.toolName}`, 20, 30)
  doc.text(`Path: ${report.toolPath}`, 20, 37)
  doc.text(`Score: ${report.score}/10 (${report.grade})`, 20, 44)
  doc.text(`Date: ${new Date(report.completedAt).toLocaleString()}`, 20, 51)

  // Red Flags Table
  if (report.redFlags.length > 0) {
    doc.setFontSize(16)
    doc.text('Red Flags', 20, 65)

    const tableData = report.redFlags.map(flag => [
      flag.severity.toUpperCase(),
      flag.category,
      flag.title,
      flag.description.substring(0, 100) + (flag.description.length > 100 ? '...' : '')
    ])

    autoTable(doc, {
      startY: 70,
      head: [['Severity', 'Category', 'Title', 'Description']],
      body: tableData,
      styles: { fontSize: 8 },
      headStyles: { fillColor: [59, 130, 246] }
    })
  }

  // Save
  doc.save(`ux-audit-${report.toolName}-${report.id}.pdf`)
}

async function exportMarkdown(report: AuditReport) {
  const markdown = `# User Experience Audit Report

## Overview

- **Tool:** ${report.toolName}
- **Path:** ${report.toolPath}
- **Score:** ${report.score}/10 (${report.grade})
- **Date:** ${new Date(report.completedAt).toLocaleString()}

## Red Flags

${report.redFlags.map(flag => `
### ${flag.severity.toUpperCase()}: ${flag.title}

**Category:** ${flag.category}

**Description:** ${flag.description}

${flag.evidence ? `
**Evidence:**
${flag.evidence.map(e => `- ${e}`).join('\n')}
` : ''}

${flag.fix ? `
**Recommended Fix:** ${flag.fix}
` : ''}

---`).join('\n')}

## Score Breakdown

Detailed findings and scoring methodology available in the full dashboard view.

---
*Generated by User Experience CLI Audit Tool*
`

  // Download as markdown file
  const blob = new Blob([markdown], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `ux-audit-${report.toolName}-${report.id}.md`
  a.click()
  URL.revokeObjectURL(url)
}
